/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2019-02-16 14:48:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/javaAllWorkSpace/freetime/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/javaAllWorkSpace/freetime/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/free/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1493978810868L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>图书管理系统</title>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/index.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav nav_check\">\r\n");
      out.write("\t\t\t\t<!-- <a href=\"BookController?method=getBook\">图书查询<span class=\"sr-only\">(current)</span> -->\r\n");
      out.write("\t\t\t\t\t<li class=\"active\" ><a href=\"#\">图书查询<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">用户查询</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">借书登记</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">增加图书</a></li>\r\n");
      out.write("        \t\t\t<li><a href=\"#\">增加用户</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">基础信息修改<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu menu_two\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">书籍信息修改</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">用户信息修改</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">逾期费用修改</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">欢迎admin,^_^</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\">修改登录信息<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu exit\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"uppwd\">修改登录密码</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"loginout\">退出登录</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.container-fluid -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"container show\">\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">图书信息查询</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t<form action=\"findBook\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"请输入图书名字查找对应图书\" name = \"bookname\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"搜索\" id=\"enter\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">图书编号</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">图书名字</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">图书作者</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">图书价格</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">图书库存</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"bookname\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"author\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>￥<input type=\"text\" name=\"unitprice\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"pricture\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">用户信息查询</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t<form action=\"findReader\" method=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"请输入读者名字查找对应图书\" name=\"name\" >\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"搜索\" id=\"enter\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">用户姓名</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">用户编号</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">用户性别</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">用户年龄</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"success\">用户电话</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"readerid\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"sex\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"age\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"phone\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">借书登记</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t\t<form action=\"addBorrowInfo\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户账号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书编号</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"readerid\" placeholder=\"请输入用户账号\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"bookid\" placeholder=\"请输入图书编号\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">增加图书</h3>\r\n");
      out.write("\t\t\t<form action=\"addBook\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书编号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书名字</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书作者</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书价格</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\" placeholder=\"请输入图书编号\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"12\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"bookname\" placeholder=\"请输入图书名字\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"我们的明天\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"author\" placeholder=\"图书作者\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"2016软件技术\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>￥<input type=\"text\" name=\"unitprice\" placeholder=\"请输入图书价格\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"5.3\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"pricture\" placeholder=\"请输入图书库存\" value=\"4\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">增加用户</h3>\r\n");
      out.write("\t\t\t<form action=\"addReaderer\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户账号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户名字</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户年龄</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户性别</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户电话</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"readerid\" placeholder=\"请输入用户账号\"\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"name\" placeholder=\"请输入用户名字\"\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"age\" oninput=\"value=value.replace(/[^\\d]/g,'')\" placeholder=\"用户年龄\"\r\n");
      out.write("\t\t\t\t\t\t\t></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input\ttype=\"radio\" value=\"男\" name=\"sex\" checked=\"checked\">男\r\n");
      out.write("\t\t\t\t\t\t\t<input\ttype=\"radio\" value=\"女\" name=\"sex\">女\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" oninput=\"value=value.replace(/[^\\d]/g,'')\" name=\"phone\" placeholder=\"用户电话\"\r\n");
      out.write("\t\t\t\t\t\t\t>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">书籍信息修改</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"请输入图书编号\">\r\n");
      out.write("\t\t\t\t<div class=\"sou\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-search\"> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书编号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书名字</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书作者</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书价格</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1612205109\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"我们的明天\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"2016软件技术\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>￥<input type=\"text\" name=\"\" value=\"5.3\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">用户信息修改</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"请输入图书编号\">\r\n");
      out.write("\t\t\t\t<div class=\"sou\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-search\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户姓名</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户编号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户性别</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户年龄</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">用户电话</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\" value=\"张三\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1612205109\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\" value=\"男\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\" value=\"12\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" value=\"138888888\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"show_main\">\r\n");
      out.write("\t\t\t<h3 class=\"title\">逾期信息修改</h3>\r\n");
      out.write("\t\t\t<div class=\"sreach\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" placeholder=\"输入图书编号\">\r\n");
      out.write("\t\t\t\t<div class=\"sou\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-search\"> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-condensed table-hover table-bordered\">\r\n");
      out.write("\t\t\t\t\t<!-- On rows -->\r\n");
      out.write("\t\t\t\t\t<!-- On cells (`td` or `th`) -->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书编号</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">图书名字</th>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"success\">逾期费用</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1612205109\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"\" disabled=\"disabled\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"我们的明天\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>￥<input type=\"text\" name=\"\" value=\"3.5\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">提交</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
